export const Colors = {
  primary: '#7C3AED',
  primaryLight: '#EDE9FE',
  accent: '#F9A8D4',
  accentBg: '#FDF2F8',
  textDark: '#1E1B4B',
  textMuted: '#6B7280',
  textLight: '#FFFFFF',
  background: '#FFFFFF',
  surface: '#F8F7FC',
  border: '#E5E7EB',
  danger: '#EF4444',
  dangerLight: '#FEE2E2',
  success: '#22C55E',
  successLight: '#DCFCE7',

  // Legacy aliases (used by FilterModal, etc.)
  primaryBlue: '#7C3AED',
  primaryLilac: '#A855F7',
  secondaryBlue: '#6D28D9',
  gradientStart: '#7C3AED',
  gradientEnd: '#A855F7',
  backgroundLight: '#FFFFFF',
  red: '#EF4444',
  lightGray: '#F3F4F6',
  redLight: '#FEE2E2',
  green: '#22C55E',
  textGray: '#6B7280',
};